- name: Deploy app with Docker
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Stop old Docker container
      community.docker.docker_container:
        name: myapp
        state: absent

    - name: Run container with Docker
      community.docker.docker_container:
        name: myapp
        image: myapp:latest
        state: started
        published_ports:
          - "5000:5000"

